name: password_strength_checker
description: Generate secure passwords, check for exposed passwords, get visual feedback for strength or get form validation with a minimum password strength required.
version: 1.2.4
issue_tracker: https://github.com/dariowskii/password_strength_checker/issues
topics: [password, generator, password-strength]
homepage: https://github.com/dariowskii/password_strength_checker
repository: https://github.com/dariowskii/password_strength_checker

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: Simple use of PasswordStrengthChecker
    path: assets/demo.gif
  - description: Generate Secure password
    path: assets/demo_generator.gif
